# Generated by Django 5.0.3 on 2024-03-29 08:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee2',
            fields=[
                ('emp_ssn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_designation', models.CharField(max_length=10)),
                ('emp_shed', models.CharField(max_length=100)),
                ('emp_dept', models.CharField(max_length=100)),
                ('emp_efficiency', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='NewJob',
            fields=[
                ('part_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewMachine',
            fields=[
                ('machine_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('max_life_expectancy_in_mm', models.FloatField()),
                ('cost', models.FloatField()),
                ('length_cut_so_far', models.FloatField()),
                ('no_of_brk_points', models.IntegerField(default=None, null=True)),
                ('tool_efficiency', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift_number', models.IntegerField()),
                ('shift_efficiency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftEfficiency',
            fields=[
                ('shift_number', models.IntegerField(primary_key=True, serialize=False)),
                ('shift_efficiency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ToolChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_code', models.CharField(max_length=50)),
                ('no_of_brk_points', models.IntegerField()),
                ('tool_efficiency', models.FloatField()),
                ('part_no_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Performs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('shift_number', models.IntegerField()),
                ('shift_duration', models.FloatField()),
                ('partial_shift', models.IntegerField()),
                ('target', models.IntegerField()),
                ('achieved', models.IntegerField()),
                ('emp_ssn', models.ForeignKey(db_column='emp_ssn', on_delete=django.db.models.deletion.CASCADE, to='webapp.employee2')),
                ('machine_id', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.CASCADE, to='webapp.newmachine')),
            ],
        ),
        migrations.CreateModel(
            name='Reviving',
            fields=[
                ('tool_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('length_used', models.FloatField()),
                ('expected_length_remaining', models.FloatField()),
                ('reason', models.CharField(max_length=100)),
                ('change_time', models.DurationField()),
                ('no_of_min_into_shift', models.IntegerField()),
                ('machine_id', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.CASCADE, to='webapp.newmachine')),
                ('replaced_by', models.ForeignKey(db_column='replaced_by', on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_replaced_by', to='webapp.tool')),
                ('tool_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_tool_code', to='webapp.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('part_no', models.ForeignKey(db_column='part_no', on_delete=django.db.models.deletion.CASCADE, to='webapp.newjob')),
                ('machine_id', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.CASCADE, to='webapp.newmachine')),
                ('tool_code', models.ForeignKey(db_column='tool_code', on_delete=django.db.models.deletion.CASCADE, to='webapp.tool')),
            ],
            options={
                'unique_together': {('machine_id', 'tool_code')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('depth_of_cut', models.FloatField()),
                ('no_of_holes', models.IntegerField()),
                ('operation_no', models.IntegerField()),
                ('part_no', models.ForeignKey(db_column='part_no', on_delete=django.db.models.deletion.CASCADE, to='webapp.newjob')),
                ('tool_code', models.ForeignKey(db_column='tool_code', on_delete=django.db.models.deletion.CASCADE, to='webapp.tool')),
            ],
            options={
                'unique_together': {('part_no', 'tool_code')},
            },
        ),
    ]
