# Generated by Django 4.2.11 on 2024-04-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviving1",
            fields=[
                (
                    "tool_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="webapp.tool",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Reviving",
        ),
    ]
