# Generated by Django 4.2.11 on 2024-05-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performs",
            name="machine_id",
            field=models.CharField(max_length=255),
        ),
    ]
