# Generated by Django 4.2.11 on 2024-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_alter_performs_machine_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakdown",
            name="achieved",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breakdown",
            name="shift_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="performs",
            name="incentive_received",
            field=models.FloatField(default=0.0),
        ),
    ]
