# Generated by Django 4.2.11 on 2024-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_breakdown_emp_ssn_alter_breakdown_change_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performs",
            name="date",
            field=models.DateField(),
        ),
    ]
