# Generated by Django 5.1 on 2024-08-09 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_breakdown_achieved_breakdown_shift_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="tool_code",
            field=models.ForeignKey(
                blank=True,
                db_column="tool_code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="webapp.tool",
            ),
        ),
    ]
